# Generated by Django 5.0.6 on 2024-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='anmol2003@gmail.com', max_length=254),
        ),
    ]
