# Generated by Django 5.0.6 on 2024-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(default='DefaultName', max_length=100),
        ),
    ]
